config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ads do
    resources :bows, :arrows, :bow_accessories, only: [:new, :create, :edit, :update]
    # resources :arrows, only: [:new, :create, :edit, :update]
    # resources :arc_accessories, only: [:new, :create, :edit, :update]
  end

  resources :bows, :arrows, :bow_accessories, only: [:destroy]

  get "my_account", to: "my_accounts#show", as: :my_account
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  belongs_to :bow
  belongs_to :arrows
  belongs_to :bow_accessory
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arrow.rb
class Arrow < ApplicationRecord
  has_many :ads
end

app/models/bow.rb
class Bow < ApplicationRecord
  has_many :ads
end

app/models/bow_accessory.rb
class BowAccessory < ApplicationRecord
  has_many :ads
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :ads
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @ads = policy_scope(Ad)
    @markers = @ads.geocoded.map do |ad|
      {
        lat: ad.latitude,
        lng: ad.longitude
      }
    end
  end

  def show
  end

  def new
    @ad = Ad.new
    authorize @ad
  end

  def create
    @ad = Ad.new(ad_params)
    @ad.user = current_user
    authorize @ad
    if @ad.save
      redirect_to ad_path(@ad)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @ad.update(ad_params)
    redirect_to ad_path(@ad)
  end

  def destroy
    @ad.destroy
    redirect_to ads_path
  end

  private

  def set_ad
    @ad = Ad.find(params[:id])
    authorize @ad
  end

  def ad_params
    params.require(:ad).permit(:title, :equipment, :price, :state, :description, :address, photos: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
  include Pundit

  # # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bows_controller.rb
class BowsController < ApplicationController
  def new
    @bow = Bow.new
  end

  def create
    @bow = Bow.new(bow_params)
    @ad = Ad.find(params([:ad_id]))
    @bow.ad = @ad
    if @bow.save
      redirect_to ad_path(@ad), notice: "Votre annonce a été créée avec succès."
    else
      render :new
    end
  end

  private

  def bow_params
    params.require(:bow).permit(
      :mark,
      :power,
      :waist,
      :matter
    )
  end
end

app/controllers/my_accounts_controller.rb
class MyAccountsController < ApplicationController
  def show
    @ads = current_user.ads
    authorize current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/edit.html.erb
<div class="container">
  <h1>Modifier une annonce</h1>
    <%= simple_form_for(@ad) do |f| %>
      <%= f.input :title %>
      <%= f.input :equipment %>
      <%= f.input :price %>
      <%= f.input :state %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.submit %>
    <% end %>
</div>

app/views/ads/index.html.erb
<div class="container">
  <h2>Toutes les Annonces</h2>

  <ul>
    <% @ads.each do |ad| %>
      <li><%= link_to ad.title, ad_path(ad) %></li>
    <% end %>
  </ul>

  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/ads/new.html.erb
<div class="container">
  <h1>Créer une nouvelle annonce</h1>
    <%= simple_form_for(@ad) do |f| %>
      <%= f.input :title, 
                  label: "Titre de l'annonce", 
                  placeholder: "Arc classic....." %>
      <%= f.input :equipment, 
                  collection: ["Arcs","Flèches","Accessoires de l'Arc"],
                  label: "Matériel", 
                  placeholder: "Arc, flèches, ....." %>
      <%= f.input :price, 
                  label: "Prix", 
                  placeholder: "0,00€" %>
      <%= f.input :state,
                  collection: ["Très bon état","Bon état","Moyen","Abimé"], 
                  label: "Etat", 
                  placeholder: "Bon état" %>
      <%= f.input :description, 
                  label: "Description" %>
      <%= f.input :address, 
                  label: "Lieux", 
                  placeholder: "1 rue de la republique, Paris 75000" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>

      <%= f.submit "Etape suivante", class: 'btn btn-primary'%>
    <% end %>
</div>

app/views/ads/show.html.erb
<div class="container">
  <% @ad.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>

  <h2><%= @ad.title %></h2>
    <p><%= @ad.equipment %></p>
    <p><%= "#{@ad.price}€" %></p>
    <p><%= @ad.state %></p>
    <p><%= @ad.description %></p>
    <p><%= @ad.address %></p>
</div>

app/views/bows/new.html.erb
<div class="container">
  <h2>Informations de l'Arc</h2>

  <%= simple_form_for do |f| %>
    <%= f.input :mark,
                label: "Marque de l'arc",
                placeholder: "Hoyt" %>
    <%= f.input :power,
                label: "Puissance de l'arc",
                placeholder: "30 livres" %>
    <%= f.input :waist,
                label: "Taille de l'arc",
                placeholder: "70 pouces" %>
    <%= f.input :matter,
                label: "Matière de l'arc" %>
    <%= f.submit "Créer l'annonce", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMonArc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>

  <div class="footer">
    <div class="container">
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
    </div>
  </div>
</html>

app/views/my_accounts/show.html.erb
<div class="container">
  <h1>Mon compte</h1>
    <%= current_user.name %>
    <%= current_user.email %>
  
  <h3>Mes annonces</h3>
    <ul>
      <% @ads.each do |ad| %>
        <li><%= ad.title %> - <%= ad.equipment %> - <%= ad.price %> - <%= ad.state %> - <%= ad.description %> - <%= ad.address %>
        <%= link_to "Modifier #{@ad.title}",
                edit_ad_path(@ad),
                method: :edit
              %>
        <%= link_to "Suprimer #{@ad.title}",
                ad_path(@ad),
                method: :delete,
                data: { confirm: "Êtes-vous sûr?" } %>
        </li>
      <% end %>
    </ul>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.topevents4.me/Htdocs/Images/Pictures/4125.jpg?puid=b4203bca-3d2a-46da-b816-d31e21185253.png);"> 
    <div class="container">
      <h1>Mon Arc</h1>
      <p>Achat et vente de matériel d'occasion</p>
    </div>
</div>
<div class="container">
  <h3 class="text-center mt-4 mb-4">Toutes les Annonces</h3>
    <div class="btn-center">
      <%= link_to "Voir toutes les annonces", ads_path, class: "btn btn-primary" %>
    </div>
</div>
<div class="container">
  <div class="box">
    <h3 class="text-center mt-4 mb-4">Toutes les Catégories</h2>
    <div class="row">
      <div class="col-sm-3">
        <div class="card">
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.ffta.fr/sites/ffta/files/styles/image-content/public/field/image/464646464664.jpg?itok=Epi9wkQG.jpg)">
            <a href="#" class="btn btn-primary">les Arcs</a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="card">
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://vincent-lalande.fr/1817-large_default/fleche-carbon-express-pile-driver.jpg)">
            <a href="#" class="btn btn-primary">Les Flèches</a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="card">
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://2.bp.blogspot.com/-hy8V70expFU/T37UisxBVOI/AAAAAAAABhk/SZZRwW2c_TU/s1600/9_Viseur_9486.jpg)">
            <a href="#" class="btn btn-primary">les Accessoirs de l'Arc</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_mon_arc.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Acceuil", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Créer une annonce", new_ad_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Mon compte", my_account_path, class: "dropdown-item" %>
            <%= link_to "Se déconecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <% if policy(Ad).new? %>
            <%= link_to "Créer une annonce", new_ad_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "S'identifier", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>